### ISSUE TITLE
panic with echo disabled

### ISSUE THREAD

**Issue by bfallik** [senseyeio/roger#23]
Hi,

I can reliably generate a panic by disabling echo within a session:
```go
	session, err := rClient.GetSession()
	if err != nil {
		log.Fatal(err)
	}
	defer session.Close()

	pkt := session.SendCommand(`options(echo = FALSE)`)
	v, err := pkt.GetResultObject()
```

results in

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
_vendor/github.com/senseyeio/roger/sexp.parseReturningOffset(0xc82000e7e4, 0x2c, 0x2c, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bfallik/sandbox/gillnet/go/src/_vendor/github.com/senseyeio/roger/sexp/factory.go:26 +0xc41
_vendor/github.com/senseyeio/roger/sexp.parseVector(0x13d6c0, 0xc82000e840, 0xc82000e7e4, 0x2c, 0x2c, 0x29, 0x2c, 0x0, 0x0, 0xc, ...)
	/Users/bfallik/sandbox/go/src/_vendor/github.com/senseyeio/roger/sexp/xt-vector.go:33 +0xbd
_vendor/github.com/senseyeio/roger/sexp.parseReturningOffset(0xc82000e7e4, 0x2c, 0x2c, 0x20, 0x0, 0x0, 0x7a15d, 0x0, 0x0)
	/Users/bfallik/sandbox/go/src/_vendor/github.com/senseyeio/roger/sexp/factory.go:68 +0x78e
_vendor/github.com/senseyeio/roger/sexp.Parse(0xc82000e7e4, 0x2c, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bfallik/sandbox/go/src/_vendor/github.com/senseyeio/roger/sexp/factory.go:13 +0x61
_vendor/github.com/senseyeio/roger.(*packet).GetResultObject(0xc82000e810, 0x0, 0x0, 0x0, 0x0)
	/Users/bfallik/sandbox/go/src/_vendor/github.com/senseyeio/roger/packet.go:77 +0x31e
main.main()
	/Users/bfallik/sandbox/go/src/tools/rogercmd/main.go:49 +0x4ed

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by dareid** [comment]
Thanks for the issue. The cause of the problem seems to have been the parsing of a list containing just a single item. This has been fixed and your options command should now run, if not, feel free to reopen.
As a sidenote, this fix has highlighted another parsing issue, which will currently raise a warning log message - I will raise an issue for this momentarily.
Thanks again!

**Comment by bfallik** [comment]
No problem, thanks for the fix!
